default:
  root_dir: "/data/CW3E_Streamflow_Archive/"
  stat_location: "/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "/Data/a7jensen/station_location2.csv"
  streamflow_data_path: ""
  manual_streamflow_data_path: "/Data/"
  stage_data_path: "/Data/a7jensen/"
  precip_data_path: "/Data/a7jensen"
  photo_data_path: "Data/seogle/"


anahita:
  root_dir: "C:/Users/anahi/OneDrive/Documents/GitHub/CW3E.StreamflowDashBoard/data/"
  stat_location: "CW3E_Streamflow_Archive/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "CW3E_Streamflow_Archive/Data/a7jensen/station_location2.csv"
  streamflow_data_path: "CW3E_Streamflow_Archive/"
  manual_streamflow_data_path: "CW3E_Streamflow_Archive/Data/"
  stage_data_path: "CW3E_Streamflow_Archive/Data/a7jensen/"
  precip_data_path: "CW3E_Streamflow_Archive/Data/a7jensen"
  photo_data_path: "CW3E_Streamflow_Archive/Data/seogle/"

garrett:
  root_dir: "C:/Users/Garrett/Documents/GitHub/CW3E.StreamflowDashBoard/data/"
  stat_location: "CW3E_Streamflow_Archive/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "CW3E_Streamflow_Archive/Data/a7jensen/station_location2.csv"
  streamflow_data_path: "CW3E_Streamflow_Archive/"
  manual_streamflow_data_path: "CW3E_Streamflow_Archive/Data/"
  stage_data_path: "CW3E_Streamflow_Archive/Data/a7jensen/"
  precip_data_path: "CW3E_Streamflow_Archive/Data/a7jensen"
  photo_data_path: "CW3E_Streamflow_Archive/Data/seogle/"

sarah:
  root_dir: "/Users/cloudy-guest/Documents/GitHub/StreamflowDashboard/data/"
  stat_location: "CW3E_Streamflow_Archive/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "CW3E_Streamflow_Archive/Data/a7jensen/station_location2.csv"
  streamflow_data_path: "CW3E_Streamflow_Archive/"
  manual_streamflow_data_path: "CW3E_Streamflow_Archive/Data/"
  stage_data_path: "CW3E_Streamflow_Archive/Data/a7jensen/"
  precip_data_path: "CW3E_Streamflow_Archive/Data/a7jensen"
  photo_data_path: "CW3E_Streamflow_Archive/Data/seogle/"  