default:
  root_dir: "/data/CW3E_Streamflow_Archive/"
  stat_location: "/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "/Data/a7jensen/station_location2.csv"
  processed_csv_path: "/Data/CLD/Processed/"
  streamflow_data_path: "/Data/"
  stage_data_path: "/Data/a7jensen/"
  precip_data_path: "/Data/a7jensen/"


anahita:
  root_dir: "C:/Users/anahi/OneDrive/Documents/GitHub/CW3E.StreamflowDashBoard/data/"
  stat_location: "CW3E_Streamflow_Archive/Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "CW3E_Streamflow_Archive/Data/a7jensen/station_location2.csv"
  processed_csv_path: "CW3E_Streamflow_Archive/"
  streamflow_data_path: "CW3E_Streamflow_Archive/Data/"
  stage_data_path: "CW3E_Streamflow_Archive/Data/a7jensen/"
  precip_data_path: "CW3E_Streamflow_Archive/Data/a7jensen"
