default:
  current_working_dir: "/app_data"
  stat_location: "/app_data/Data/Stream/CW3E_Stations_all.csv"
  stat_location2: "/app_data/station_location2.csv"
  precip: "/app_data/Data/Stream/BCC_all_precip.xlsx"
  processed_csv_path: "/app_data/Data/CLD/Processed/"
  streamflow_data_path: "/app_data/Data/CW3E_Streamflow_Archive/Data/"
  stage_data_path: "/app_data/"


anahita:
  current_working_dir: "C:/Users/anahi/OneDrive/Documents"
  stat_location: "GitHub/R-shiny/Data/Stream/CW3E_Stations_all.csv"
  stat_location2: "/Users/anahi/OneDrive/Documents/GitHub/CW3E.StreamflowDashBoard/station_location2.csv"
  precip: "GitHub/R-shiny/Data/Stream/BCC_all_precip.xlsx"
  processed_csv_path: "Z:/CW3E_Streamflow_Archive/CLD/Processed/"
  streamflow_data_path: "Z:/CW3E_Streamflow_Archive/Data/"
  stage_data_path: "/Users/anahi/OneDrive/Documents/GitHub/CW3E.StreamflowDashBoard/"
