default:
  root_dir: "/opt/StreamflowDashboard/data/CW3E_Streamflow_Archive/"
  stat_location: "Data/a7jensen/CW3E_Stations_all.csv"
  stat_location2: "Data/a7jensen/station_location2.csv"
  streamflow_data_path: ""
  manual_streamflow_data_path: "Data/"
  stage_data_path: "Data/a7jensen/"
  precip_data_path: "Data/a7jensen/"
  photo_data_path: "Data/a7jensen/"
  ratingcurve_data_path: "UDC/Processed/"
