default:
  root_dir: "/app_data"
  stat_location: "/Data/Stream/CW3E_Stations_all.csv"
  stat_location2: "/station_location2.csv"
  processed_csv_path: "/Data/CLD/Processed/"
  streamflow_data_path: "/Data/CW3E_Streamflow_Archive/Data/"
  stage_data_path: ""
  precip_data_path: ""


anahita:
  root_dir: "C:/Users/anahi/OneDrive/Documents/"
  stat_location: "/GitHub/R-shiny/Data/Stream/CW3E_Stations_all.csv"
  stat_location2: "/GitHub/CW3E.StreamflowDashBoard/station_location2.csv"
  processed_csv_path: "/GitHub/CW3E.StreamflowDashBoard/data/CW3E_Streamflow_Archive/"
  streamflow_data_path: "/GitHub/CW3E.StreamflowDashBoard/data/CW3E_Streamflow_Archive/Data/"
  stage_data_path: "/GitHub/CW3E.StreamflowDashBoard/"
  precip_data_path: "/GitHub/CW3E.StreamflowDashBoard/"
